### ISSUE TITLE
Pass specific nested json to ArgoCD Application helm attributes 

### ISSUE THREAD

**Issue by Coder63** [argoproj/argocd-example-apps#116]
Hi team , we are running v2.1.7 ..

We have app of apps pattern parent AppD which trigger multiple child apps like AppD1,AppD2,AppD3 etc... 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: AppD1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aqueduct
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: AppD1
    repoURL: <gitlab>
    targetRevision: {{ .Values.app_revision_to_track }}
    helm:
      values: |
        AppD: {{ toJson .Values.AppD }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
```

We pass all the values for AppD1, AppD2,AppD3,AppD4 etc from single values file.. 

```
AppD:
    var1: value1
    var2: value2
    var3: value3
    AppD1:
        foo1: bar1
        foo2: bar2
        foo3: bar3
    AppD2:
        foo1: bar1
        foo2: bar2
        foo3: bar3
    AppD3:
        foo1: bar1
        foo2: bar2
        foo3: bar3 
```

I tried to pass only AppD1 specific values to helm and it did get passed to child app (able to see inner json passed to values)  but the  deployment /resource doesn't see the values / inherit it..  

```
  helm:
      values: |
        AppD.AppD1: {{ toJson .Values.AppD.AppD1 }}
```

Is there any know bug/ limitation  around this ?
