### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by brandonros** [argoproj/argocd-example-apps#198]
After running `argocd app create guestbook --repo https://github.com/argoproj/argocd-example-apps.git --path guestbook --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse`:

```
TypeError: Cannot read properties of undefined (reading 'split')
    at controllers.js:39:45
    at angular.js:7576:11
    at A (angular.js:10965:31)
    at A (angular.js:10965:31)
    at angular.js:11051:26
    at h.$eval (angular.js:11977:16)
    at h.$digest (angular.js:11803:15)
    at h.$apply (angular.js:12083:13)
    at f (angular.js:7841:34)
    at H (angular.js:8042:7)
(anonymous) @ angular.js:9435
```

**Comment by brandonros** [comment]
I'm going to guess `gcr.io/heptio-images/ks-guestbook-demo:0.2` has an error in it?

**Comment by corneliusroemer** [comment]
Looks like it yes

**Comment by lukkuz** [comment]
After taking a closer look at the logs, it looks like `ks-guestbook-demo` has an undocumented dependency on Redis, as it fails with the following message: `<br/><b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis:6379]'`.

The fastest solution seems to be adding the Redis deployment and service definition to `argocd-example-apps/guestbook`. I tested the below and it worked OK.

guestbook/redis-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
```

guestbook/redis-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
```
