### ISSUE TITLE
Helm-Dependency does not use custom values.yaml to override values

### ISSUE THREAD

**Issue by nicolai92** [argoproj/argocd-example-apps#67]
Hello,

I tried to install an official Helm chart and overwrite the default values by using a custom `values.yaml` file. However, it looks like the default values are not overwritten, e.g. I need to use a custom Docker image and defined it in the custom `values.yaml` file, but the official Docker image of the Helm chart is pulled.

Am I missing something?

Chart.yaml

```
name: kong
```

requirements.yaml

```
dependencies:
  - name: kong
    version: 1.11.0
    repository: https://charts.konghq.com
```

custom_values.yaml

```
image:
  repository: nicolai92/kong-oidc
  tag: latest
```

The screenshot shows, that `kong:2.1` is pulled, but to my understanding it should be my custom Docker image, which is tagged with `latest`.

![Bildschirmfoto 2020-11-04 um 10 34 09](https://user-images.githubusercontent.com/3242677/98094271-575d0980-1e89-11eb-87af-3bcd230468d4.png)

**Comment by nicolai92** [comment]
I figured it out 🎉

When using a custom `values.yaml` file, you may need to wrap all the chart specific values under the `name` tag that comes from the Chart.yaml file.

So, in the official Helm chart you may need to overwrite the image with:

```
image:
  repository: nicolai92/kong-oidc
  tag: latest
```

but for ArgoCD the custom `values.yaml` has to look like this:

```
kong:
  image:
    repository: nicolai92/kong-oidc
    tag: latest
```
